services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "15432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data 
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge
