CREATE TABLE IF NOT EXISTS PUBLIC.UUIDS (
    ID UUID PRIMARY KEY, 
    NAME VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS PUBLIC.SEQUENCIAIS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS PUBLIC.SEQUENCIAIS_BIGINT (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(100)
);
