INSERT INTO PUBLIC.UUIDS VALUES ('65f6ce7b-0682-4075-8a2a-b865ae848831', 'First Name');
INSERT INTO PUBLIC.UUIDS VALUES ('6686f234-f670-430c-b781-c08d1a175e19', 'Second Name');
INSERT INTO PUBLIC.UUIDS VALUES ('5f1430ba-804f-4d85-be17-ff51fb90bd7b', 'Third Name');
INSERT INTO PUBLIC.UUIDS VALUES ('60a6b8eb-347e-422c-aa15-ec7cf91a4fed', 'Fourth Name');

INSERT INTO PUBLIC.SEQUENCIAIS (NAME) VALUES ('First Name');
INSERT INTO PUBLIC.SEQUENCIAIS (NAME) VALUES ('Second Name');
INSERT INTO PUBLIC.SEQUENCIAIS (NAME) VALUES ('Third Name');
INSERT INTO PUBLIC.SEQUENCIAIS (NAME) VALUES ('Fourth Name');

INSERT INTO PUBLIC.SEQUENCIAIS_BIGINT (NAME) VALUES ('First Name');
INSERT INTO PUBLIC.SEQUENCIAIS_BIGINT (NAME) VALUES ('Second Name');
INSERT INTO PUBLIC.SEQUENCIAIS_BIGINT (NAME) VALUES ('Third Name');
INSERT INTO PUBLIC.SEQUENCIAIS_BIGINT (NAME) VALUES ('Fourth Name');